apiVersion: v1
kind: Pod
metadata:
  name: java
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: arjunachari12/k8s-demo
    ports:
    - name: java-port
      containerPort: 3000
